name: Phenoix Test Automation workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "30 18 * * *"
  workflow_dispatch:
   inputs:
      env:
       description: "Environment"
       type: choice
       options: [qa,uat,dev]
       default: qa
       required: true
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Executing Test Automation Frameowrk
      run: mvn clean test -DsuiteXmlFile=testng.xml -Denv="${{ github.event.inputs.env }}"

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: SureFire reports
        path: target/surefire-reports/
        retention-days: 10
        

   
